Pull Request for #16: Make heatmaps compatible with SK
JMSLab/BootstrapReport pull request #17
Opened 2023-11-17 22:23 UTC by rcalvo12

In this issue, I edited the heatmap function in `_diagnostics.py` to allow users to make heatmaps using the SK distance as well as the TV distance. 

I also added a bounds and vrange argument so that users can zoom into the plot with more control and control the color scaling of the heatmap. These are very easy to remove if necessary.

2023-11-17 22:28 UTC, jmshapir requested changes
@rcalvo12 thanks!

Had a small suggestion on the plot title and also suggesting to switch default behavior to plotting SK.

Adding @MosesStewart for code review.

Thanks both!

2023-11-17 22:28 UTC, jmshapir commented on src/BootstrapReport/_diagnostics.py
> +    def _heat_map(self, distance = "TV", density = 50, bounds = [], vrange = [0,1], outfile = False):
```suggestion
    def _heat_map(self, distance = "SK", density = 50, bounds = [], vrange = [0,1], outfile = False):
```

2023-11-17 22:28 UTC, jmshapir commented on src/BootstrapReport/_diagnostics.py
> +        plt.title(f'{distance}D with varied µ and σ')
```suggestion
        plt.title(f'{distance} with varied µ and σ')
```

2023-11-18 00:05 UTC, MosesStewart approved these changes

2023-11-18 00:05 UTC, MosesStewart commented
@rcalvo12 all the code changes look good to me!

2023-11-18 00:16 UTC, jmshapir commented
@MosesStewart thanks!

If we accept my suggested edits does it look like the code will run successfully?

If so can you implement those edits and wrap up the pull please?

Thanks!

2023-11-19 20:06 UTC, jmshapir commented
@MosesStewart fyi you can prioritize https://github.com/JMSLab/BootstrapReport/pull/17#issuecomment-1817278185 ahead of #18 thanks.

2023-11-19 21:20 UTC, MosesStewart commented
> @MosesStewart thanks!
> 
> If we accept my suggested edits does it look like the code will run successfully?
> 
> If so can you implement those edits and wrap up the pull please?
> 
> Thanks!

Sorry ~ I just noticed this comment. The changes look correct ~ indistinguishable from a `python` master!

2023-11-19 21:24 UTC, jmshapir approved these changes

2023-11-19 23:19 UTC, merged

2023-11-19 23:20 UTC, MosesStewart commented
Summary in https://github.com/JMSLab/BootstrapReport/issues/16#issuecomment-1818011649